[versions]

agp-version = "8.0.1"
kotlin-version = "1.8.21"
kotlin-ksp-version = "1.8.21-1.0.11"

[libraries]

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp-version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-version" }
kotlin-symbol-processing = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "kotlin-ksp-version" }
junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }

[bundles]
classpath = ["android-gradle-plugin", "kotlin-gradle-plugin"]

[plugins]
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp-version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }